spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mydatabase
    password: my-secret-pw
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: 'true'
